# Generated by Django 3.2.7 on 2022-10-23 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_stripe', '0003_price_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feature',
            old_name='description',
            new_name='description_en',
        ),
        migrations.AddField(
            model_name='feature',
            name='description_fr',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='productfeature',
            name='active',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
